### ISSUE TITLE
Changing the style forces the page to reload

### ISSUE THREAD

**Issue by myshov** [privatenumber/vite-css-modules#11] opened 2024-11-06 18:28 UTC
### Problem

It looks like the page reloads when the page receives HMR event
1. Open the demo and wait 5 seconds until dynamic item is added to the page
2. Try to change css file, for example color of the  text in css declaration for `.hello`

### Expected behavior

App should retain local state (dynamically added item) on update of styles, but instead the page reloads

### Minimal reproduction URL

https://stackblitz.com/edit/vitejs-vite-x9tc9v?file=src%2Fstyle.module.css

### Version

v1.6.0

### Node.js version

v20.16.0

### Package manager

npm

### Operating system

macOS

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment] 2024-11-07 04:06
This behavior is expected due to a limitation with HMR in vanilla JavaScript modules. When editing a CSS Module imported by JavaScript, Vite triggers a full page reload because vanilla JS modules lack native HMR capabilities for runtime swapping, which also affects CSS Modules since they can't handle stateful updates by default.

This can be reproduced in a plain Vite setup: editing a CSS Module imported by JS will trigger a full reload. However, Vite has a known bug where changes in composed CSS Modules aren't detected, so it may not even trigger a reload in those cases (as noted in the README).

Vite's HMR works seamlessly with frameworks like React and Vue, which have state management to support atomic updates. For CSS Modules, HMR doesn't work if exported class names are altered since these changes can't be dynamically swapped. However, if the exported class names remain the same, it may be possible to support HMR by only replacing the stylesheet, reapplying the new styles without a reload.

I'm open to a pull request exploring this enhancement. For now, I'll close this as it's not a bug, but contributions are welcome if you'd like to pursue this functionality.

**Closed by privatenumber** 2024-11-07 04:06 UTC
Labels: bug
